### ISSUE TITLE
Minimum Test Coverage

### ISSUE THREAD

**Issue by Joshuaerinosho** [stelynx/dart-full-coverage#16]
Hi. It will be really nice if a minimum test coverage could be set in the actions. For example:
```Dart
- uses: stelynx/dart-full-coverage@v1.0.5
        with:
          package: egakcap
          min_coverage: 95
          ignore: "*_state.dart, do_not_import_me.dart"
```

**Comment by campovski** [comment]
Hm, what information should this `min_coverage` convey?

**Comment by Joshuaerinosho** [comment]
@campovski  The idea to enforce a minimum code coverage threshold. If the code coverage is below the specified percentage, the action fails and if it's up to the specified percentage, the action should pass.

**Comment by campovski** [comment]
This is somewhat hard to implement. Because the actual coverage in percentage is calculated by coverage service, like codecov; the purpose of this repository is to make sure that all files (even unchanged) are counted when computing the coverage percentage by coverage services.

For example, given codecov which we always use, you can set in their own configuration the threshold for coverage percentage that is passable for you, e.g. you set 95%, if the coverage is let's say 94%, the codecov GitHub app will mark your PR as failing the CI.

I understand your wish however it seems a bit of a redundancy given that all major coverage tools already support this feature.

However, this would be an interesting and challenging task to do. If you feel that this action needs this, we would be glad to add this functionality, although we are currently really busy and would take us some time before we can tackle it.

**Comment by Joshuaerinosho** [comment]
Alright. Thank you so much!

**Comment by campovski** [comment]
I assume this can be closed.
